 - name: include variables
   include_vars: all.yml
   
 - name: Checking running Docker Container
   become: yes
   shell: docker ps -a

 - name: "Check if mysql is installed"
   package_facts:
      manager: "auto"

 - name: python installation check
   debug:
      msg: "Python found"
   when: "'python' in ansible_facts.packages"


 - name: Starting the Nginx Docker Container
   become: yes
   docker_container:
    name: "{{ webserver_name }}"
    image: "{{ webserver_image }}"
    state: started
    restart_policy: always
    ports:
     - "{{ webserver_src_port }}:{{ webserver_dest_port }}"
    # volumes: 
    #  - "{{ webserver_src_vol }}:{{ webserver_dest_vol }}:rw" 
